# Generated by Django 5.1.4 on 2025-01-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAdditionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование категории')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория движения денежных средств',
                'verbose_name_plural': 'Категории движения денежных средств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyAdditionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование статуса')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Статус движения денежных средств',
                'verbose_name_plural': 'Статусы движения денежных средств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyAdditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование типа')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тип движения денежных средств',
                'verbose_name_plural': 'Типы движения денежных средств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyAdditionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование подкатегории')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('money_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='money_addition_notes.moneyadditioncategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория движения денежных средств',
                'verbose_name_plural': 'Подкатегории движения денежных средств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyAdditionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('money_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма в рублях')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_notes', to='money_addition_notes.moneyadditioncategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_notes', to='money_addition_notes.moneyadditionstatus')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_notes', to='money_addition_notes.moneyadditionsubcategory')),
                ('money_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_notes', to='money_addition_notes.moneyadditiontype')),
            ],
            options={
                'verbose_name': 'Запись движения денежных средств)',
                'verbose_name_plural': 'Записи движения денежных средств',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='moneyadditioncategory',
            name='money_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='money_addition_notes.moneyadditiontype', verbose_name='Тип'),
        ),
    ]
