# Generated by Django 5.1.4 on 2025-01-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_addition_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyadditionnote',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_notes', to='money_addition_notes.moneyadditioncategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='moneyadditionnote',
            name='money_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_notes', to='money_addition_notes.moneyadditiontype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='moneyadditionnote',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_notes', to='money_addition_notes.moneyadditionstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='moneyadditionnote',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_notes', to='money_addition_notes.moneyadditionsubcategory', verbose_name='Подкатегория'),
        ),
    ]
