# Generated by Django 5.1.4 on 2025-01-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_addition_notes', '0002_alter_moneyadditionnote_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyadditionnote',
            name='comment',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Комментарий'),
        ),
    ]
