# Generated by Django 5.1.4 on 2025-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_addition_notes', '0005_alter_moneyadditionnote_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyadditioncategory',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='moneyadditioncategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Нужен для обращения к элементам. Генерируется автоматически', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='moneyadditionstatus',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Наименование статуса'),
        ),
        migrations.AlterField(
            model_name='moneyadditionstatus',
            name='slug',
            field=models.SlugField(blank=True, help_text='Нужен для обращения к элементам. Генерируется автоматически', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='moneyadditionsubcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Наименование подкатегории'),
        ),
        migrations.AlterField(
            model_name='moneyadditionsubcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Нужен для обращения к элементам. Генерируется автоматически', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='moneyadditiontype',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Наименование типа'),
        ),
        migrations.AlterField(
            model_name='moneyadditiontype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Нужен для обращения к элементам. Генерируется автоматически', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
